# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipsterElk
services:
  postgresql:
    image: postgres:17.4
    # volumes:
    #   - ~/volumes/jhipster/jhipsterElk/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jhipsterElk
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - '127.0.0.1:5432:5432'
